# Generated by Django 6.0.7 on 2026-08-05 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('license_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Licensed'), ('EXPIRED', 'License Expired'), ('CANCELLED', 'License Cancelled / Suspended')], default='ACTIVE', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('contact', models.CharField(blank=True, default='', max_length=200)),
                ('source_url', models.URLField(default='https://foreignjob.dofe.gov.np')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(default='MANUALLY_CURATED', max_length=100)),
                ('source_note', models.CharField(default='manually curated, not government-verified', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('contact', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Consultancies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(default='Hipolabs/Wikipedia', max_length=100)),
                ('recognized', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_entity_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=50)),
                ('user_phone', models.CharField(blank=True, default='', max_length=50)),
                ('user_email', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('email_sent', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verification_type', models.CharField(max_length=50)),
                ('input_name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('matched_entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('matched_entity_type', models.CharField(blank=True, default='', max_length=50)),
                ('license_status', models.CharField(blank=True, default='', max_length=100)),
                ('match_score', models.FloatField(default=0.0)),
                ('verdict', models.CharField(choices=[('SAFE', 'Safe 🟢'), ('SUSPICIOUS', 'Suspicious 🟡'), ('HIGH_RISK', 'High Risk 🔴'), ('UNKNOWN', 'Unknown ⚪')], default='UNKNOWN', max_length=50)),
                ('verdict_display', models.CharField(blank=True, default='', max_length=255)),
                ('suspicious_phrases', models.JSONField(blank=True, default=list)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('source_info', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
