# Generated by Django 6.0.8 on 2026-08-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='Consultancy',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
